### ISSUE TITLE
Implement `Stats()` from Task trait

### ISSUE THREAD

**Issue by Mossaka** [containerd/runwasi#208]
The Stats() rpc should return runtime cgroup metrics for a task. This includes
1. cpu core usage
2. memory usage
3. network io

Lukily, the `containerd-shim` crate already provides a nice helper function to collect process cgroup stats, given a PID of a running container: https://github.com/containerd/rust-extensions/blob/9836036cc3282284ad078d9944b5c4395e201f92/crates/shim/src/cgroup.rs#L97-L127

We can use `collect_metrics` function to implement this Stats() function in `containerd-shim-wasm`

**Question**: shall we collect runtime specific metrics for a running container from `wasmtime` and `wasmedge`? If so, what kind of metrics do we want to collect? @devigned @cpuguy83 @jsturtevant @jprendes

**Comment by jsturtevant** [comment]
sounds good!  The response should be in format that containerd knows about so it can translate them in CRI if possible, otherwise might need to update containerd. Which we might want to do eventually for WASM specific metrics?

See 
https://github.com/containerd/containerd/blob/81895d22c9ee091db6f9371e3177b50744fe2edb/pkg/cri/server/container_stats.go#L35 and https://github.com/containerd/containerd/blob/81895d22c9ee091db6f9371e3177b50744fe2edb/pkg/cri/server/container_stats_list_linux.go#L36

**Comment by Mossaka** [comment]
It looks like `collect_metrics` only supports v1 cgroup :(
