### ISSUE TITLE
Containerd breaking change in main branch

### ISSUE THREAD

**Issue by Mossaka** [containerd/runwasi#475]
> currently on the main branch containerd only issues shim delete for the sandbox during sandbox cleanup.

ref: https://github.com/containerd/containerd/issues/9727

**Comment by squillace** [comment]
thanks a ton for looking into this, @Mossaka

**Comment by Mossaka** [comment]
I ran all our tests against the main branch containerd and all passed.

**Comment by jsturtevant** [comment]
from the issue it looks like we just need to avoid mixing shim versions https://github.com/containerd/containerd/issues/9727#issuecomment-1958594294

> So, it looks unsafe to use current podsandbox mode to integrate with old version shim. That's why I say that we should update shim doc and highlight it changelog.

I tried to add a nightly job using kind but it didn't work since Kind currently fails to load images since it can't parse the new containerd config version 3 yet.

https://github.com/containerd/runwasi/compare/main...jsturtevant:runwasi:add-nightly-contianerd-job?expand=1

If fails with `ERROR: failed to detect containerd snapshotter` since kind image loader parses the wrong config layout: https://github.com/kubernetes-sigs/kind/blob/c83316d25e1c40f1c66982b637edf3ee34a5e0d4/pkg/cluster/nodeutils/util.go#L105-L108

**Comment by Mossaka** [comment]
Closing this issue as it won't affect the runwasi shims.
