### ISSUE TITLE
Missmatch docs and build

### ISSUE THREAD

**Issue by erkules** [containerd/runwasi#567]
Building runwasi I get (shown for wasmtime for simplicity):
~~~
containerd-shim-wasmtime-v1
containerd-shim-wasmtime-v1.d
~~~

The docs talk about:
~~~
- containerd-shim-[ wasmedge | wasmtime | wasmer ]-v1
- containerd-shim-[ wasmedge | wasmtime | wasmer ]d-v1
- containerd-[ wasmedge | wasmtime | wasmer ]d
~~~
So there is a suffix missmatch  (v1.d vs. d-v1)

I also miss how to build the **d and how to run it

**Comment by Mossaka** [comment]
Thanks for raising this issue, yes the docs and the built artifacts are mismatched because we have integrated all the binaries into one binary. the `containerd-shim-wasmtime-v1` binary uses `argv[0]` to decide to run as 
- `containerd-shim-wasmtime-v1`
- `containerd-shim-wasmtimed-v1`
- `containerd-wasmtimed`

https://github.com/containerd/runwasi/blob/main/crates/containerd-shim-wasm/src/sandbox/cli.rs#L66-L78

**Comment by erkules** [comment]
Ok, maybe I should have installed it. Building on for remote machines I intentionally missed that step thx.
Is there an example how to run containerd-wasmtimed?
