### ISSUE TITLE
need investigate:  `cross test` failed with exit code 0

### ISSUE THREAD

**Issue by Mossaka** [containerd/runwasi#685]
run: https://github.com/containerd/runwasi/actions/runs/11112905312/job/30876017101?pr=682#step:9:373

_Originally posted by @Mossaka in https://github.com/containerd/runwasi/issues/682#issuecomment-2384668489_

**Comment by fawadasaurus** [comment]
I spent some time on this. I believe that the issue is actually with buildx: https://github.com/docker/buildx/issues/732

**Comment by Mossaka** [comment]
What would you suggestr as a walkaround? @fawadasaurus

**Comment by fawadasaurus** [comment]
Github now offers ARM64 (in addition to AMD64) runners for Windows and Linux. So would it be viable to use a matrix of different runners for builds / tests?

I am curious if using the native runner for each build/test is a viable alternative to Cross and meets the needs that originally led to using Cross.

What do you think @Mossaka ?

**Comment by Mossaka** [comment]
I think one of the goals to use cross is that we want to build statically-linked binaries. But I agree with you that we may investigate native runners for each build/test. 

Jorge had a PR #737 that fixed this issue.

**Comment by jprendes** [comment]
We currently do not run the tests in arm64, using native runners would be interesting if it allows us to run them.

The reason not to run them in arm64 is because cross uses qemu to run the tests when the arch doesn't match, and that didn't translate properly to the syscalls we use to create the containers. Using native runners would fix that.
