### ISSUE TITLE
failed to start shim: start failed: terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by diannaowa** [containerd/runwasi#91]
run the following:
`ctr run --rm --runtime=io.containerd.wasmedge.v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest testwasm /wasi-demo-app.wasm echo 'hello'`

And get errors:
`ctr: failed to start shim: start failed: terminate called after throwing an instance of 'std::out_of_range'
  what():  bitset::reset: __position (which is 1) >= _Nb (which is 1)
: signal: aborted (core dumped): unknown`

OS:
root@VM-0-10-ubuntu:~# cat /etc/issue
Ubuntu 20.04.6 LTS \n \l

**Comment by WeixinX** [comment]
I had the same problem.

My Settings are as follows:
```bash
# OS
$ uname -a
Linux utils2 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# WasmEdge
$ wasmedge -v
wasmedge version 0.12.0

# containerd
$ ctr version
Client:
  Version:  v1.7.0
  Revision: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
  Go version: go1.20.2

Server:
  Version:  v1.7.0
  Revision: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
  UUID: 1c4d0805-ee6f-440b-bfe6-b3cc6ca3d1c5

# containerd-shim-wasmedge-v1
v0.3.3
```
<br />

And I run my own wasm container:
```bash
$ ctr i pull docker.io/weixinx/hello-wasm:latest
$ ctr run --rm --runtime io.containerd.wasmedge.v1 docker.io/weixinx/hello-wasm:latest hello

# But the error is as follows:
ctr: failed to start shim: start failed: /usr/local/bin/containerd-shim-wasmedge-v1: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/containerd-shim-wasmedge-v1)
```
<br />

The information for the wasm container is as follows:
main.go:
```go
package main

import "fmt"

func main() {
    fmt.Println("Hello TinyGo from WasmEdge!")
}
```
Compile using `tinygo`:
```bash
$ tinygo build -o hello.wasm -target wasi main.go
```
Dockerfile:
```Dockerfile
FROM scratch
ADD hello.wasm /
CMD ["/hello.wasm"]
```

**Comment by 0xE282B0** [comment]
Hi @WeixinX,
Ubuntu 20.04 seems to be shipped with a glibc 2.31. You either need to upgrade your glibc to 2.32 or recompile the shim with an older version of Ubuntu, so it is linked against a glibc<=2.31. In your case 20.04 or before.

**Comment by WeixinX** [comment]
@0xE282B0, thank you. 
But before I upgraded glibc, I had this error:
```bash
ctr: failed to start shim: start failed: /usr/local/bin/containerd-shim-wasmedge-v1: /lib/x86_64-linux-gnu/libc.so.6:  Version ` GLIBC_2. 32 'not found (required by/usr/local/bin/containerd - shim - wasmedge - v1)
```
<br >

Then I tried to upgrade glibc. Here's how I upgraded glibc:
```bash
$ vim /etc/apt/sources.list
# Append the following
deb http://cz.archive.ubuntu.com/ubuntu jammy main
# Save and exit

$ apt-get update
$ apt-get install libc6
```
<br >

Result:
```bash
$ strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_
GLIBC_2.2.5
...
GLIBC_2.31
GLIBC_2.32
GLIBC_2.33
GLIBC_2.34
GLIBC_2.35
GLIBC_PRIVATE
```
<br >

Then execute the ctr command again and get the previous error :(

**Comment by WeixinX** [comment]
@0xE282B0 @diannaowa


I seem to have solved the problem by reinstalling `WasmEdge` (v0.12.0 -> 0.11.2).


Let me briefly outline my process:
1. First, I installed the default WasmEdge according to [WasmEdge Installation And Uninstallation](https://wasmedge.org/book/en/quick_start/install.html#wasmedge-installation-and-uninstallation):
```bash
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
```
According to the [install.py](https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.py#L1434), we can know that the default installation is the latest version, that is v0.12.0.


2. Then I downloaded `containerd-shim-wasmedge-v1-v0.3.3` in [second-state/runwasi release](https://github.com/second-state/runwasi/releases/tag/v0.3.3)


3. Then I built my own wasm container and ran it, but got the error:
```bash
$ ctr i pull docker.io/weixinx/hello-wasm:latest
$ ctr run --rm --runtime io.containerd.wasmedge.v1 docker.io/weixinx/hello-wasm:latest hello
ctr: failed to start shim: start failed: terminate called after throwing an instance of 'std::out_of_range'
  what():  bitset::reset: __position (which is 1) >= _Nb (which is 1)
: signal: aborted (core dumped): unknown
```


4. I tried to build `containerd-shim-wasmedge-v1` myself based on [containerd/runwasi](https://github.com/containerd/runwasi). But I ran into [compatibility issues](https://github.com/containerd/runwasi/issues/101#issuecomment-1495339943) during the build. Therefore I changed the version of `WasmEdge` (v0.12.0 -> v0.11.2):
```bash
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.11.2
```
 Finally I built and ran my wasm container successfully.


5. To determine where the problem was, I replaced `containerd-shim-wasmedge-v1` ([containerd/runwasi](containerd/runwasi) -> [second-state/runwasi](https://github.com/second-state/runwasi)). I found that my wasm container was still running fine.


So I tentatively concluded that there seems to be some compatibility issues between `WasmEdge v0.12.0` and `containerd-shim-wasmedge-v1`.
But I don't know how it works. So I still need some help.

**Comment by Mossaka** [comment]
Close this one as it's resolved.
